- scripts/template_createoffers.json
Adds a template for createoffers.json. User needs to edit values as per their preferences and name the file createoffers.json
> Add template for market making script's json config file

- basicswap/__init__.py
- basicswap/basicswap.py
- basicswap/templates/header.html
- basicswap/templates/offers.html
- basicswap/templates/smsgaddresses.html
- basicswap/ui/page_automation.py
- basicswap/ui/page_bids.py
- basicswap/ui/page_offers.py
- basicswap/ui/page_smsgaddresses.py
- doc/release-notes.md
Add persistent filters.
show only active bid and offer counts.
Add titles for offer clock states.
> ui: Add persistent filters, show only active bid and offer counts.

- bin/basicswap_prepare.py
commit hash is from here: 
https://github.com/monero-project/monero-site/commit/1bdb0d456943a224a4d6241b1bb713172e5fa29f
> Update monero 0.18.2.2 to 0.18.3.1

- bin/basicswap_prepare.py
Related: https://github.com/tecnovert/basicswap/commit/237d12afa0198ea8357d72bb405cb7e7cb8e71d5
> add ltc min_fee_relay

- basicswap/templates/offers.html
Fixes rate calculation for Your offers
> ui: offers: rate fix, color change, text size

- basicswap/templates/offers.html
Misaligned the amount. (left and right) Fixed here
> fix a misalignment introduced in my lastest commit

- basicswap/templates/header.html
- basicswap/templates/offers.html
- Added extra details on the Your Offers page.
- Added function sortTable for time/rate/market.
- Various fixes.
> ui: Offers page / Clean-up / sortTable / Fixes

- basicswap/interface/xmr.py
- basicswap/templates/settings.html
- bin/basicswap_prepare.py
> monero: v0.18.3.3 [dev branch]

- basicswap/templates/footer.html
- basicswap/templates/header.html
- basicswap/templates/offers.html
- basicswap/templates/wallet.html
- basicswap/templates/wallets.html
- Fix wownero rates on offers page.
- Fix wownero USD price on wallet/wallets page.
- Set dark mode as default.
- Fix tooltips.
- Fix JS errors.
> Fix wownero rate + bug fixes.

- basicswap/templates/offers.html
- different decimals per coin
- zano rate via cryptocompare
- uniform widget content
> ui: coingecko change pct

- bin/basicswap_prepare.py
> firo: v0.14.13.3 (mandatory)

- bin/basicswap_prepare.py
update monero to latest release
> monero: v0.18.3.4

- basicswap/base.py
- basicswap/basicswap.py
- basicswap/http_server.py
- basicswap/js_server.py
- basicswap/templates/footer.html
- basicswap/templates/header.html
- basicswap/templates/offers.html
- basicswap/templates/unlock.html
- basicswap/ui/page_tor.py
- Restructured and refactored the JS for the Offers page.
- Integrated TOR for API requests related to charts, rates, and coin prices.
- Implemented a new chart (better layout) with options to toggle coin volume and refresh the chart + clearing the cache upon refresh.
- Added a 10-minute cache for all API requests, with an option for manual refresh.
- Disabled notifications for new offers to reduce spam, notifications for new bids and bid acceptances remain active.
- BSX on load will now redirect @ network offers page.
- Applied various minor fixes.
- Use readURL (if in basicswap.json "use_tor": true, it will use TOR as default, if false it will use clearnet for APIs)
> ui: Refactor offers page / Added TOR <> API / Cache

- basicswap/static/css/style.css
- basicswap/templates/error.html
- basicswap/templates/header.html
- basicswap/templates/info.html
- Styled info/error templates.
- Disable shutdown button when swap is in progress.
- Added modal for shutdown.
- Wallet long address input fix.
> ui: Style info/error templates + disable shutdown button when swap is in progress.

- basicswap/static/js/offerstable.js
- basicswap/static/js/pricechart.js
- basicswap/templates/offers.html
- Updated the spinning animation for enabling/disabling the auto-refresh chart (now 3 seconds).
- Added fiat denomination (USD) to the fiat value.
- Moved fiat denomination to the top and fixed colors for dark theme compatibility.
- Fixed: Offers appearing multiple times when using filters.
- Fixed: Filters on offers / sentoffers table. (Filter bids / Filter offers / Filter Sending / Filter Receiving 
- Bug/Fix: Added a unique filter ID for each listing to prevent duplicates.
- UI: Removed USD values from the "Max Send" and "Max Receive" columns.
- UI: All offers in the order book, including your own, should be displayed on the right with other order book offers.
- Fixed: Chart initial load after startup wasn’t loading prices for the tiles, requiring a manual refresh.
- Fixed: Minor bug …
> ui: Main price chart fixes/updates.

- basicswap/static/js/offerstable.js
Temp fix for sorting if more than 1 page
> ui: 100 offers per page

- basicswap/static/js/offerstable.js
`Savings` -> `Loss` when losing
Use `-` to indicate negative values
> ui: market rate tooltip fix

- basicswap/templates/offer.html
- basicswap/ui/page_offers.py
> ui: Add modal for confirm send bid.

- basicswap/templates/offer.html
- basicswap/templates/offer_new_1.html
Logic:
User selects "new address" = next time, "new address" should be preselected.
User selects "old addr 1" = next time, old addr 1 should be selected.
User selects "old addr 2" = next time, old addr 2 should be selected.
> ui: Update logic of "New Address"

- basicswap/static/js/offerstable.js
- basicswap/static/js/pricechart.js
- basicswap/templates/offers.html
- Using websockets for real time update of network offers / your offers.
- Removed timers (no need anymore).
- Fixed header show order book stats number (will update in real time).
- Fixed network offers / your offers footer stats.
- When filter on x coin, no overwrite and it respects users filter setting, it will also use websockets and update the table on x coin filter. 
- Fixes any potential JS memory leak.
- Various small fixes.
- Clean up old code in the JS.
- Every time the offers table updates (whether from new WebSocket messages, filtering, pagination, or manual refresh), it will: Check if the price cache is older than 1 minute (60000ms) If prices are older than 1 minute: Fetch fresh prices from CoinGecko Update the latestPrices variable Store new prices in cache If prices are …
> Websockets for new listings (real time) on network/your offers table + Fix potential JS memory leaks.

- basicswap/bin/prepare.py
> prepare: throw error on removal of part

- basicswap/bin/prepare.py
- basicswap/interface/xmr.py
> wownero: v0.11.3.0

- basicswap/templates/offer.html
- You can enter either the sending or receiving amount, and it will automatically calculate the other amount based on the rate of the swap.
- If rate is negotiable (true) it will automatically calculate sending and receiving amounts.
- UX and Layout improvements.
> ui: Update new bid section.

- basicswap/bin/prepare.py
Hardfork, mandatory
https://github.com/dashpay/dash/blob/v22.0.0/doc%2Frelease-notes.md
> dash: v22.0.0 HF

- basicswap/static/js/offerstable.js
- basicswap/static/js/pricechart.js
- basicswap/templates/offers.html
- Unused event listeners: Listeners are properly cleaned up.
- Caching DOM elements: DOM elements are properly cleared when no longer needed. Tooltips and elements are properly removed.
- Global variables: Global state is properly cleaned up in the cleanup() function.
- Closure memory leak, event handlers now use proper binding through eventManager.
- Added WebSocket cleanup.
- Added cache cleanup.
- Added timer management.
- Bug/fix on manual refresh button.
- Update cleanup function.
- Better error handling API / Tooltips: Rate, Market and API status feedback.
- Fix Firo API issue with rate/market tooltips.
- Reduced retry delay.
- Pricechart fix potential mem leaks.
- Fix scroll up / down memory increase bug.
- Simplified API requests and remove debug.
- Improve identity fetching + …
> Fix potential sources of mem leaks + Various related fixes.

- basicswap/static/js/pricechart.js
> JS: Decimals

- basicswap/basicswap.py
- basicswap/interface/ltc.py
> prepare: fix mweb wallet generation

- basicswap/bin/prepare.py
> help: add --upgradecores

- basicswap/static/js/bids_sentreceived.js
- basicswap/static/js/bids_sentreceived_export.js
- basicswap/static/js/global.js
- basicswap/static/js/modules/api-manager.js
- basicswap/static/js/modules/cache-manager.js
- basicswap/static/js/modules/cleanup-manager.js
- basicswap/static/js/modules/config-manager.js
- basicswap/static/js/modules/identity-manager.js
- basicswap/static/js/modules/memory-manager.js
- basicswap/static/js/modules/network-manager.js
- basicswap/static/js/modules/summary-manager.js
- basicswap/static/js/modules/tooltips-manager.js
- basicswap/static/js/modules/wallet-manager.js
- basicswap/static/js/modules/websocket-manager.js
- basicswap/static/js/new_offer.js
- basicswap/static/js/pricechart.js
- basicswap/static/js/swaps_in_progress.js
- basicswap/static/js/ui/dropdown.js
- basicswap/templates/offer_new_1.html
move to debug_ui
deduplicate
djlints
eslints
> create offer: move amt and rate vari to debug_ui

- basicswap/static/js/offers.js
- Update rates whenever new offer date is received via WebSocket.
- Ensure rates are updated when the offers table is refreshed.
- Keep profit/loss in sync.
> Fix: Update orderbook rates.

- basicswap/js_server.py
- basicswap/static/js/bids_available.js
- basicswap/static/js/modules/api-manager.js
- basicswap/static/js/modules/coin-manager.js
- basicswap/static/js/modules/config-manager.js
- basicswap/static/js/modules/price-manager.js
- basicswap/static/js/modules/wallet-manager.js
- basicswap/static/js/modules/websocket-manager.js
- basicswap/static/js/offers.js
- basicswap/static/js/pricechart.js
- basicswap/static/js/swaps_in_progress.js
- basicswap/templates/footer.html
- basicswap/templates/header.html
- basicswap/templates/offers.html
- basicswap/templates/unlock.html
- Removed seperate API calls for BTC / WOW + Removed extra rate calls.
- Fixes offers table not refreshing + prices.
- Price tiles + Offerstable price now in sync.
- Fixed sortTable bug / Fix sorting market +/-
- price-manager.js
- Added coin-manager.js
- Various fixes.
- Swap in Progress (Using swaps_in_progress dictionary)
- Bump version GUI v.3.2.1
- AutoRefreshEnabled true as default.
> Extra refactor + Various bug/fixes.

- basicswap/static/js/bids_sentreceived.js
- basicswap/static/js/bids_sentreceived_export.js
- basicswap/static/js/modules/api-manager.js
- basicswap/static/js/modules/cache-manager.js
- basicswap/static/js/modules/cleanup-manager.js
- basicswap/static/js/modules/memory-manager.js
- basicswap/static/js/modules/price-manager.js
- basicswap/static/js/modules/tooltips-manager.js
- basicswap/static/js/offers.js
- basicswap/static/js/pricechart.js
- basicswap/static/js/ui/bids-tab-navigation.js
- basicswap/templates/bids.html
- basicswap/templates/header.html
- Price tiles to display accurate BTC/satoshi per coin conversion.
- Resolved volume display issue for BCH and Firo currencies.
- Upgraded/Fixed JavaScript modules: memory-manager, tooltip-manager, and cleanup-manager.
- Memory: Eliminated redundant console.log() statements across multiple pages, preventing log accumulation on network offers page when developer tools are active.
- Improved header navigation: clicking on bids now directs to the ALL tab, with bid counters properly routing to sent/received tabs.
- Add ALL tab/table on bids page.
- Bids export add ALL + minor fixes.
- Various minor fixes and optimizations.
> Fix: Price Tiles / (JS) Better memory cleanup/manager / Improved header / ALL tab/table on bids page + Various fixes.

- basicswap/static/js/amm_tables.js
sorted numerically and into proper categories
removed ethereum
> amm: sort+restrict adaptor & secret hash

- basicswap/interface/wow.py
i had set to 3 but looks like it's actually 4
> wow: coins unlock after 4 confirmations

- basicswap/basicswap.py
- basicswap/bin/prepare.py
~~draft only because it will need to be rebased after 332~~
ready and rebased
> wow: cleanup some dups in prepare.py and basicswap.py

- basicswap/static/js/amm_tables.js
- basicswap/static/js/bids_sentreceived_export.js
- basicswap/static/js/modules/api-manager.js
- basicswap/static/js/modules/cleanup-manager.js
- basicswap/static/js/modules/memory-manager.js
- basicswap/static/js/modules/tooltips-manager.js
- basicswap/static/js/pricechart.js
- basicswap/static/js/ui/bids-tab-navigation.js
- basicswap/templates/amm.html
add and edit amm screens were different sizes on large screens
Swapped the icons so the amount you're offering is beside the icon. (same as your offers and orderbook)
+ some whitespace linting
> amm: icon beside amount & consistent size of add/edit

- basicswap/bin/prepare.py
> xmr: v0.18.4.1

- basicswap/interface/xmr.py
> xmr: retry on transient error.
