bin/basicswap_prepare.py

1. using `transfer_split` instead of `transfer`.
please confirm changes were done correctly before merge 
https://www.getmonero.org/resources/developer-guides/wallet-rpc.html#transfer_split
related but doesn't close: https://github.com/tecnovert/basicswap/issues/2
2. I assume "blocks_confirned" to be "wait x blocks before spendable". If so, monero is 10. (changed from 7)
edit: `blocks_confirmed` is in regards to transaction finality - when to release. In this case, 7 seems excessive. Changed to 3.
for comparison, litecoin is 2 (5min). Monero was 7 (14mins). Changing to 3 = 6mins

Monero: Release funds after 3 confirmations + [discussion] transfer > transfer_split

---

basicswap/interface/xmr.py
basicswap/templates/offers.html
basicswap/templates/settings.html

Changed fee to priority 2 (normal), which is adequate for 1-2 block inclusion. 
Monero is designed to auto(0) select between fee lvl 1 and 2 depending on backlog. Due to a bug in monero wallet software, its not auto elevating. 
Monero is releasing a fix in the coming days. 
Will revert these changes when
1. Spam stops or 
2. Monero has released the fix and bsx users have had time to update
@tecnovert please check that i make the changes properly

monero: auto fee bypass to normal until fixed upstream

---

README.md

Not everyone using Element for Matrix, with matrix.to links people can choose a client.

Replace Element links with Matrix page

---

basicswap/interface/wow.py

quickfix:
Wownero has a 5 minute block time and only requires 3 confirmations (15min) to unlock the funds. Currently is using 10 confirmations (50min)

wownero: only 3 confirmations required

---

bin/basicswap_prepare.py

Firo has an upcoming hardfork on or around 2024-09-16. Updating is mandatory

firo: v0.14.14.0 hardfork 2024-09-16 (mandatory)

---

.cirrus.yml
Dockerfile
doc/install.md
doc/notes.md

- docs: git clone the basicswap_v0.2 tag
- dependencies: remove wget and unzip
- dependencies: install wheel before sqalchemy to get rid of errors
- install: edit node used for monero height
- notes: update monero example
- notes: use `coincurve-basicswap` folder instead of `coincurve` for windows
closes #116

docs: update install docs

---

scripts/createoffers.py
tests/basicswap/extended/test_scripts.py

If min_amount is set offers will be created for amounts between "min_coin_from_amt" and "amount" in increments of "min_amount".

script: Add min_amount offer setting.

---

basicswap/static/js/offerstable.js

ui: remove dup USD from market rate tooltip

---

scripts/createoffers.py

This allows `min_coin_from_amt` to be set to a lower value than `amount_step`. 
user story:
balance 1.5 LTC
Increment 1 LTC
Reserve 0.2 LTC
Result: 
Reserve gets bumped to 1 LTC, leaving 0.5 LTC available to be sold. Because the increment is 1 LTC, but only 0.5 LTC is available, the order will not post due to low balance.
Expected:
Post offers until balance would fall below 0.2 + 1.0 (reserve + increment).
This PR allow setting values below the increment when amount_step is present in config, and uses default behavior when `amount_step` is not configured.
When `amount_step` is present in config but `min_coin_from_amt` is not, it assumes the user wants to sell their full balance - it sets `min_coin_from_amt` to 0.  (perhaps this value should have a buffer for tx fees?)

scripts: allow setting reserve below increment

---

basicswap/bin/prepare.py

- disable/enable `manage_wallet_daemon`
- don't require starting up the part daemon if the `addcoin` coin is only editing basicswap.json

prepare: disablecoin/addcoin for manage_wallet_daemon

---

basicswap/basicswap.py
basicswap/interface/xmr.py

optimizations for monero and monero-based coins
we now call `refresh` manually if `open_wallet` fails on windows, and only `close_wallet` if open_wallet fails

 ux: XMR optimizations

---

basicswap/interface/part.py
scripts/createoffers.py

1. Fixed correct Anon and Blind PART balance checks in createoffers.py
2. Fixed the getUnspentByAddr to retrieve correctly the Blind PART UTXOs
Note: Consider changing the filter in the listunspent and listunspentblind to 0 confirmations since when one sends to PART to themselves the wallet balances are shown instantly (as opposed to "pending") or make sure that any balances with 0 confirmations are shown as pending. I think the latter is a more intuitive option

Fix part balances checks

---

basicswap/basicswap.py
basicswap/interface/xmr.py

Old behavior:
open_wallet > auto_refreshes after a few seconds. The same "no connection" error would be thrown, but wouldn't be caught. busy/syncing daemon triggers this error.. and if no bootstrap daemons are found, same error
this should behave similarly.

interface: xmr.py allow startup with a busy daemon

---

README.md

Version 0.14.2 [now supports Bitcoin Cash](https://particl.news/basicswap-version-0-14-2-and-gui-3-1-1-now-available/). This PR adds Bitcoin Cash to the list of available assets on the main README.md

Add Bitcoin Cash to Available Assets on README.md

---

basicswap/basicswap.py
basicswap/js_server.py
basicswap/static/css/style.css
basicswap/static/js/offerstable.js
basicswap/templates/offer_new_1.html
basicswap/templates/offers.html
basicswap/ui/page_offers.py

- UI: Added private orderbook display in the network offers / your offers table.
**(Based on) To send a private offer:**
Recipient creates a new address to receive offers on.
Recipient sends the pubkey for the newly created address to the offerer.
Offerer imports the recipient's pubkey.
Offerer sends a new offer to the recipients key instead of the public network.
(Nodes will ignore offers sent on keys other than the network key or keys created for offer-receiving.)
- UI: Added filter for all/public/private.
- UI: New offers page, fixed address + note/label display on network/address select (before they all displayed as none).
- Identity will update stats on successful trades for buyer/seller (note: Not network wide - only between buyer/seller)
- UI: Updated tooltips in the details …

Private orderbook display + Identity stats + Various fixes.

---

basicswap/templates/wallet.html

- Other wallets (xmr, wow, ltc) have the "main" or transparent addr on the left. This moves part wallet to be consistent with those
- center qr code for coins with only 1 address 
- remove duplicate code for reseed section

wallet: misc wallet.html

---

basicswap/bin/prepare.py
basicswap/bin/run.py

Differences from preparebinonly:
- If with/withoutcoins isn't set
- Read list of coins to update from basicswap.json
- Only where manage_daemon or manage_wallet_daemon is true
- Store core version no in basicswap.json
- Only update if missing or differs.
- Writes core_version_no and core_version_group to basicswap.json
- Per core updated
- Backup old config to timestamped file

Add upgradecores function to prepare script.

---

basicswap/templates/offers.html

L/R scrolling inaccessible in all browser sizes. This brings back the scrollbar on screens sized sm and below

offers: fix overflow bar

---

basicswap/static/js/pricechart.js
basicswap/templates/offers.html

https://tailwindcss.com/docs/responsive-design#targeting-mobile-screens
> Where this approach surprises people most often is that to style something for mobile, you need to use the unprefixed version of a utility, not the sm: prefixed version. Don’t think of sm: as meaning “on small screens”, think of it as “at the small breakpoint“.
md here is too soon of a breakpoint and causes content to extend beyond element. lg works.

ui: responsive offers page

---

basicswap/templates/wallet.html

- removed fee rates (incorrect) and estimates (unavail) for xmr/wow
- set containers to lg+ for mobile responsive view
- hid expected seed check if true
- reduced some duplicated code
- changed some `if` to `elif`
- fixed most djlints (img attributes untouched)
- various small fixes

wallet: resposive ui & cleanup

---

basicswap/basicswap.py
basicswap/bin/prepare.py
basicswap/chainparams.py
basicswap/interface/btc.py
basicswap/interface/dcr/dcr.py
basicswap/interface/firo.py
basicswap/interface/ltc.py
basicswap/interface/nav.py
basicswap/interface/wow.py
basicswap/interface/xmr.py
tests/basicswap/extended/test_wow.py
tests/basicswap/test_xmr.py

Removed "walletfile" setting for XMR and WOW, replaced with "wallet_name". 
Set wallet_name in prepare script with eg: BTC_WALLET_NAME env var.

Add wallet_name option to basicswap.json.

---

basicswap/basicswap.py
basicswap/bin/prepare.py
basicswap/chainparams.py
basicswap/contrib/test_framework/descriptors.py
basicswap/interface/btc.py
tests/basicswap/common.py
tests/basicswap/common_xmr.py
tests/basicswap/test_btc_xmr.py
tests/basicswap/test_xmr.py

Set BTC_USE_DESCRIPTORS env var to true to enable descriptors in the prepare script and test_btc_xmr A separate watchonly wallet is created when using descriptor wallets.

Add BTC descriptor wallet support.

---

basicswap/interface/xmr.py

problem: When starting up xmr with an out-of-sync wallet, or a new wallet using an untrusted daemon, the "always-on" refresh (introduced in #74) causes wallet-rpc (and bsx) to be unresponsive until finished syncing. Noticable during startup or creating a new instance while using an untrusted daemon.
fix: This returns previous behavior to only refresh under certain circumstances.
note: wallet-rpc being non-responsive while syncing is an upstream monero issue that i hope will be fixed sooner rather than later, as its an issue for numerous projects.

ux: revert xmr universal refresh to fix regression

---

basicswap/bin/prepare.py

brings important changes
- fixes wallet-rpc startup delay on a new mainnet wallet that calls refresh
- fixed close wallet bug

xmr: bump to v0.18.4.0

---

basicswap/basicswap.py
basicswap/interface/wow.py
basicswap/interface/xmr.py
tests/basicswap/test_xmr.py

monero-wallet-rpc v0.18.4.0 actually reports the full error instead of just `Failed to open wallet`. This allows us to properly handle issues. An example being when a wallet cache file is corrupted. The cache file is the file w/o the `.keys` extension
this pr catches the error and wont let basicswap start if the wallet cache file is corrupted.
This pr also removes the "store" command that preceeds close_wallet (it was fixed upstream). Had to add override to wownero until wow rebases

xmr: detect corrupt wallets

---

basicswap/bin/prepare.py

Upcoming hard fork at block 1,104,500 (approximately 28 May 2025).

firo: v0.14.14.1 hardfork 2025-05-28 mandatory

---

basicswap/static/js/bids_sentreceived.js
basicswap/templates/bids.html
basicswap/templates/header.html

- inconsistent hidden column on small screens
- adjust and consolidate ststus columns
- bid totals in header tooltip were too high. Not sure hor the old numbers were calculated, replaced with the macro from the tab counds on send/received bids tabs/buttons

bids: cosmetic fixes

---

basicswap/ui/util.py

occasionally (when using amount step), you'll run into the "mantissa too long" error upon creating an offer. This just rounds the offer's inputAmount

utils: round inputAmount to avoid mantissa err

---

basicswap/bin/prepare.py
basicswap/bin/run.py
basicswap/interface/btc.py
basicswap/interface/part.py
basicswap/templates/debug.html
basicswap/ui/page_debug.py
tests/basicswap/common.py
tests/basicswap/test_btc_xmr.py

Set changetype=bech32 in BTC and LTC .conf files.
Rewrite .conf files to add changetype at startup if possible.
Add combine_non_segwit_prevouts function to coin interface.
Add option to list non-segwit UTXOs and combine_non_segwit_prevouts to gui.
Add test for changetype and combine_non_segwit_prevouts.

prepare: Set changetype=bech32 in BTC and LTC .conf files.

---

basicswap/static/js/offers.js

New: show markup: market @ $5 + $15 = rate shows maker markup of 200% green when profitable, and 200% red when a loss
old: maker: market @ $5 + $15 shows maker markup of 200% green when selling, and 50% in red (loss of purchase power when buying)
the old way lead to confusion:
if i have 1 offer at 200% above market, and a competing (identical) offer exists from someone else, my offer appears as 200% on my end, but the competing offer appears as -50%

js(offers): use same rates for buying and selling

---

basicswap/basicswap.py
basicswap/bin/prepare.py
basicswap/bin/run.py
basicswap/js_server.py
basicswap/static/css/style.css
basicswap/static/js/amm_tables.js
basicswap/static/js/modules/api-manager.js
basicswap/static/js/modules/balance-updates.js
basicswap/static/js/modules/notification-manager.js
basicswap/static/js/modules/price-manager.js
basicswap/static/js/modules/summary-manager.js
basicswap/static/js/modules/wallet-manager.js
basicswap/static/js/new_offer.js
basicswap/static/js/ui/bids-tab-navigation.js
basicswap/templates/amm.html
basicswap/templates/header.html
basicswap/templates/offer_new_1.html
basicswap/templates/settings.html
basicswap/templates/wallet.html
basicswap/templates/wallets.html
basicswap/ui/page_amm.py
basicswap/ui/page_offers.py
basicswap/ui/page_settings.py
basicswap/ui/util.py

- AMM: Balances (amounts per coin / wallet) in offfer/bid add/edit.
- New offer dropdown fromt/to (amounts per coin / wallet)
- Wallet/wallets removed refresh button.
- Wallet/wallets update dynamic now (no need for refresh or full page refresh) for wallet amounts/price.
- Balances update if in/out transaction.
- New json endpoint.
- Various fixes.
- Fix intervals. 
- Fix WS trigger for pending + normal balance and in/out.
- Fix amounts scientific notation (1e-8)
- Better notifications (toasts):
New Offers: Show notifications for new network offers (disabled by default).
New Bids: Show notifications for new bids on your offers.
Bid Accepted: Show notifications when your bids are accepted.
Balance Changes: Show notifications for incoming and outgoing funds.
Outgoing Transactions: Show …

GUI: Dynamic balances (WS) + Better Notifications (Toasts) + various fixes.

---

basicswap/bin/prepare.py
basicswap/bin/run.py

I didn't test this extensively, but it worked with `--datadir`.
Resolves: #345

fix: allow relative paths in inputs

---

basicswap/static/js/pricechart.js

- If BTC is disabled, the chart will load with the first available enabled coin.

Fix BTC chart loads even if BTC is not enabled

---

basicswap/db_upgrades.py

change to avoid accepting concurrent bids that would cause you to go below your `minimum balance`. (Only works for new installs).
i also think the default time to wait for acceptance of a bid (minutes valid) can be bumped from 10 -> 30mins (i'm not sure how to do that).

automation: set max concurrent incoming bids to 1
